# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb52294096841848926fa3ef0baa4686fe61af49bca0fb92bdad3128ca46cfd92d2924215261e72dbac769c7b9d2d490e592c5dc868be62d03f1cc0d21283036

test:
  secret_key_base: 433fc41ef43004bff3967960105b501529160888396ae5fcd33c367e14449d52d32cafde0d46e422fcd2235e7f86d9e34949033de163b98dd7be2f5a7d6f7425

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
